name: Pylint & Black
run-name: "🐍 Pylint & Black (${{ github.actor }} auf ${{ github.ref_name }})"

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pylint black paramiko pywebview

      - name: break if there is no python file
        run: |
          if ! find . -name "*.py" | grep -q .; then
            echo "No Python files found. Skipping linting and formatting."
            exit 0
          fi

      - name: check if pylintrc exists
        run: |
          if [ ! -f .pylintrc ]; then
            echo "" > .pylintrc
            echo "[MASTER]" >> .pylintrc
            echo "ignore=venv" >> .pylintrc
            echo "" >> .pylintrc
            echo "[MESSAGES CONTROL]" >> .pylintrc
            echo "disable=C0114,C0115,C0116,bad-indentation,C0301,R0801" >> .pylintrc
            echo "" >> .pylintrc
            echo "[FORMAT]" >> .pylintrc
            echo "max-line-length=120" >> .pylintrc
            echo "" >> .pylintrc
            echo "[DESIGN]" >> .pylintrc
            echo "max-args=8" >> .pylintrc
            echo "max-locals=20" >> .pylintrc
            echo "max-returns=6" >> .pylintrc
            echo "max-branches=12" >> .pylintrc
            echo "max-statements=50" >> .pylintrc
            echo "max-parents=7" >> .pylintrc
            echo "max-attributes=10" >> .pylintrc
            echo "max-public-methods=20" >> .pylintrc
            echo "" >> .pylintrc
            echo "[REPORTS]" >> .pylintrc
            echo "output-format=colorized" >> .pylintrc
            echo "reports=no" >> .pylintrc
            echo "" >> .pylintrc
            echo "[TYPECHECK]" >> .pylintrc
            echo "generated-members=numpy.*,torch.*" >> .pylintrc
          fi


      - name: Lint with pylint
        run: |
          find . -name "*.py" | xargs pylint --fail-under=9

      - name: Format code with Black
        run: |
          black .

      - name: Commit changes if needed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "style: auto-format Python code with Black"
            git push origin HEAD:${{ github.ref_name }} || true
          fi
